const KEY='novaplay_full_v1';
const fresh=()=>({balance:10000,wagered:0,wins:0,losses:0,history:[],limits:{maxBet:500,sessionStart:Date.now()},muted:false});
let S=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
const save=()=>localStorage.setItem(KEY,JSON.stringify(S));
const money=n=>Math.floor(n).toLocaleString();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function add(type,amount,detail){S.history.unshift({time:new Date().toLocaleString(),type,amount,detail,balance:S.balance});S.history=S.history.slice(0,100);save();render()}
function playCost(bet){return Number(bet)>0&&Number(bet)<=S.balance&&Number(bet)<=S.limits.maxBet}
function shell(content,tab='home'){document.getElementById('app').innerHTML=`<header class="top"><div class="brand">NOVA<span>PLAY</span></div><div class="wallet"><div class="balance">🪙 <b>${money(S.balance)}</b></div><button class="btn secondary" onclick="resetDemo()">Reset Demo</button></div></header><main class="wrap"><div class="hero"><h1>Play. Win. Have Fun.</h1><p>Virtual-credit gaming platform — no real-money wagering or cash withdrawals.</p></div><div class="tabs">${[['home','Lobby'],['games','Games'],['wallet','Wallet'],['history','History'],['admin','Admin']].map(([k,t])=>`<button class="tab ${tab===k?'active':''}" onclick="nav('${k}')">${t}</button>`).join('')}</div>${content}<div class="footer">NovaPlay demo • Virtual credits only • No deposits, cash-out or real-money gambling.</div></main>`}
function nav(t){if(t==='home'||t==='games')return lobby(t);if(t==='wallet')return wallet();if(t==='history')return history();return admin()}
function lobby(tab){shell(`<section class="grid">${[['🎡','Roulette','Classic single-zero roulette','roulette'],['🎲','Dice','High / Low dice game','dice'],['🂡','Blackjack','Simple 21 card game','blackjack'],['🎰','Slots','Three-reel virtual slots','slots']].map(g=>`<div class="card game"><div><div class="icon">${g[0]}</div><h3>${g[1]}</h3><p>${g[2]}</p></div><button class="btn" onclick="game('${g[3]}')">Play</button></div>`).join('')}</section><section class="section"><div class="notice">Demo wallet starts with 10,000 virtual credits. Set a session max-bet limit in Admin.</div></section>`,tab)}
function game(g){if(g==='roulette')return roulette();if(g==='dice')return dice();if(g==='blackjack')return blackjack();return slots()}
function controls(gameName){return `<div class="bets">${[10,25,50,100,250,500].map(x=>`<button class="chip" onclick="pickBet(this,${x})">${x}</button>`).join('')}</div><input id="bet" type="number" min="1" max="${S.limits.maxBet}" placeholder="Bet amount (max ${S.limits.maxBet})"><div style="margin-top:10px"><button class="btn" onclick="${gameName}Play()">Play</button> <button class="btn secondary" onclick="nav('games')">Back</button></div>`}
function pickBet(el,n){document.querySelectorAll('.chip').forEach(x=>x.classList.remove('sel'));el.classList.add('sel');document.getElementById('bet').value=n}
function roulette(){shell(`<div class="two"><div class="card"><h2>🎡 Roulette</h2><div class="result" id="rres">Choose a number or color, then play.</div><div class="roulette">${Array.from({length:37},(_,n)=>`<button class="num ${n===0?'green zero':n%2?'red':'black'}" onclick="pickR(${n})">${n}</button>`).join('')}</div><div class="bets"><button class="chip" onclick="pickR('red')">Red</button><button class="chip" onclick="pickR('black')">Black</button><button class="chip" onclick="pickR('odd')">Odd</button><button class="chip" onclick="pickR('even')">Even</button></div></div><div class="card"><h3>Your bet</h3><div id="rpick" class="result">None</div>${controls('roulette')}</div></div>`,'games')}
let rPick=null;function pickR(x){rPick=x;document.getElementById('rpick').textContent='Selection: '+x}
function roulettePlay(){let b=Number(document.getElementById('bet').value);if(!rPick||!playCost(b))return alert('Select a bet within your balance/limit.');S.balance-=b;S.wagered+=b;let n=Math.floor(Math.random()*37),win=false,pay=0;if(typeof rPick==='number')win=n===rPick,pay=win?b*35:0;else if(rPick==='red')win=n>0&&n%2===1,pay=win?b*2:0;else if(rPick==='black')win=n>0&&n%2===0,pay=win?b*2:0;else if(rPick==='odd')win=n%2===1,pay=win?b*2:0;else if(rPick==='even')win=n>0&&n%2===0,pay=win?b*2:0;S.balance+=pay;win?S.wins++:S.losses++;add(win?'WIN':'LOSS',win?pay:-b,`Roulette result ${n}, bet ${rPick}`)}
function dice(){shell(`<div class="two"><div class="card"><h2>🎲 Dice</h2><div class="result" id="dres">Pick High or Low.</div><div class="bets"><button class="chip" onclick="dPick='low'">Low (1–3)</button><button class="chip" onclick="dPick='high'">High (4–6)</button></div></div><div class="card"><h3>Dice bet</h3>${controls('dice')}</div></div>`,'games')};let dPick='high';function dicePlay(){let b=Number(document.getElementById('bet').value);if(!playCost(b))return alert('Invalid bet.');S.balance-=b;S.wagered+=b;let n=1+Math.floor(Math.random()*6),win=dPick==='high'?n>=4:n<=3,pay=win?b*2:0;S.balance+=pay;win?S.wins++:S.losses++;add(win?'WIN':'LOSS',win?pay:-b,`Dice ${n}, ${dPick}`)}
function slots(){shell(`<div class="two"><div class="card" style="text-align:center"><h2>🎰 Slots</h2><div id="slot" style="font-size:64px;margin:35px 0">🍒 🍋 7️⃣</div><div class="result">Three matching symbols pay 8×. Two matching pay 2×.</div></div><div class="card"><h3>Spin</h3>${controls('slots')}</div></div>`,'games')};function slotsPlay(){let b=Number(document.getElementById('bet').value);if(!playCost(b))return alert('Invalid bet.');let sy=['🍒','🍋','🔔','💎','7️⃣'];let a=[0,0,0].map(()=>sy[Math.floor(Math.random()*sy.length)]);document.getElementById('slot').textContent=a.join(' ');S.balance-=b;S.wagered+=b;let mult=a[0]===a[1]&&a[1]===a[2]?8:a[0]===a[1]||a[1]===a[2]||a[0]===a[2]?2:0;let pay=b*mult;S.balance+=pay;mult?S.wins++:S.losses++;add(mult?'WIN':'LOSS',mult?pay:-b,`Slots ${a.join(' ')}`)}
function blackjack(){shell(`<div class="two"><div class="card"><h2>🂡 Blackjack</h2><div class="result" id="bj">Press Deal to play.</div><div id="hands"></div><button class="btn" onclick="bjDeal()">Deal</button></div><div class="card"><h3>Stake</h3>${controls('blackjack')}</div></div>`,'games')};function hand(){let v=[1,2,3,4,5,6,7,8,9,10,10,10,11];return [v[Math.floor(Math.random()*v.length)],v[Math.floor(Math.random()*v.length)]]}function blackjackPlay(){bjDeal()}function bjDeal(){let b=Number(document.getElementById('bet').value);if(!playCost(b))return alert('Enter a valid stake first.');let p=hand(),d=hand(),ps=p[0]+p[1],ds=d[0]+d[1];S.balance-=b;S.wagered+=b;let win=ps<=21&&(ds>21||ps>ds),tie=ps===ds&&ps<=21,pay=win?b*2:tie?b:0;S.balance+=pay;win?S.wins++:tie?null:S.losses++;document.getElementById('bj').textContent=`You ${ps} • Dealer ${ds} • ${win?'You win!':tie?'Push.':'Dealer wins.'}`;document.getElementById('hands').textContent=`Player: ${p.join(' + ')}    Dealer: ${d.join(' + ')}`;add(win?'WIN':tie?'PUSH':'LOSS',win?pay:tie?0:-b,`Blackjack ${ps} vs ${ds}`)}
function wallet(){shell(`<div class="two"><div class="card"><h2>🪙 Virtual Wallet</h2><div style="font-size:34px;margin:18px 0">${money(S.balance)} credits</div><p class="muted">No real-money deposits or withdrawals are enabled in this build.</p><button class="btn" onclick="bonus()">Claim daily demo bonus</button></div><div class="card"><h3>Session</h3><p>Wagered: ${money(S.wagered)}</p><p>Wins: ${S.wins}</p><p>Losses: ${S.losses}</p><p>Net: ${money(S.balance-10000)}</p></div></div>`,'wallet')};function bonus(){if(S.history.some(x=>x.detail==='Daily demo bonus'))return alert('Bonus already claimed in this demo.');S.balance+=1000;add('BONUS',1000,'Daily demo bonus')}
function history(){shell(`<div class="card"><h2>Transaction & Game History</h2><table class="table"><thead><tr><th>Time</th><th>Type</th><th>Amount</th><th>Detail</th><th>Balance</th></tr></thead><tbody>${S.history.length?S.history.map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.type)}</td><td>${x.amount>0?'+':''}${money(x.amount)}</td><td>${esc(x.detail)}</td><td>${money(x.balance)}</td></tr>`).join(''):'<tr><td colspan="5" class="muted">No activity yet.</td></tr>'}</tbody></table></div>`,'history')}
function admin(){shell(`<div class="stats"><div class="card stat"><span class="muted">Players</span><b>1</b></div><div class="card stat"><span class="muted">Virtual balance</span><b>${money(S.balance)}</b></div><div class="card stat"><span class="muted">Total wagered</span><b>${money(S.wagered)}</b></div><div class="card stat"><span class="muted">Net demo P/L</span><b>${money(S.balance-10000)}</b></div></div><section class="section two"><div class="card"><h2>Game Controls</h2><label class="muted">Maximum bet per game</label><div class="field"><input id="limit" type="number" min="1" max="5000" value="${S.limits.maxBet}"><button class="btn" onclick="setLimit()">Save</button></div><p class="muted">This limit applies only to virtual credits.</p></div><div class="card"><h2>Responsible Play</h2><p>Use the demo as a sandbox. No cash-out, deposits, or real-money wagering.</p><button class="btn danger" onclick="resetDemo()">Reset all demo data</button></div></section>`,'admin')};function setLimit(){let n=Math.max(1,Math.min(5000,Number(document.getElementById('limit').value)||500));S.limits.maxBet=n;save();admin()}function resetDemo(){if(confirm('Reset the demo wallet and history?')){S=fresh();save();nav('home')}}nav('home');