const express=require('express');const path=require('path');const fs=require('fs');const Database=require('better-sqlite3');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const helmet=require('helmet');const morgan=require('morgan');const PDFDocument=require('pdfkit');const XLSX=require('xlsx');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
fs.mkdirSync(path.join(__dirname,'data'),{recursive:true});const db=new Database(path.join(__dirname,'data','ledger.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'ADMIN',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,tx_date TEXT NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL DEFAULT 0,notes TEXT DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);
if(!db.prepare('SELECT COUNT(*) c FROM users').get().c){const hash=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'Admin@12345',10);db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run('Administrator',process.env.ADMIN_EMAIL||'admin@local.test',hash,'ADMIN',new Date().toISOString())}
const defaults={deposit_commission_1:'0.01',deposit_commission_2:'0.005',deposit_commission_3:'0.02',withdrawal_commission:'0.015',date_format:'YYYY-MM-DD'};for(const[k,v]of Object.entries(defaults))db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v);
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));app.use(morgan('tiny'));app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired session'})}}
function settings(){return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]))}function rates(){const s=settings();return{d1:+s.deposit_commission_1,d2:+s.deposit_commission_2,d3:+s.deposit_commission_3,w:+s.withdrawal_commission}}
function rowsFor(from,to,type,search){let q='SELECT * FROM transactions WHERE 1=1',p=[];if(from){q+=' AND tx_date>=?';p.push(from)}if(to){q+=' AND tx_date<=?';p.push(to)}if(type){q+=' AND type=?';p.push(type)}if(search){q+=' AND notes LIKE ?';p.push('%'+search+'%')}q+=' ORDER BY tx_date ASC,id ASC';return db.prepare(q).all(...p)}
function metrics(from,to){const rows=rowsFor(from,to),m={deposit:0,withdrawal:0,cash:0,upline:0,depositCount:0,withdrawalCount:0,cashCount:0,uplineCount:0};for(const r of rows){m[r.type]=(m[r.type]||0)+r.amount;m[r.type+'Count']=(m[r.type+'Count']||0)+1}m.balance=m.deposit-m.withdrawal-m.cash-m.upline;const r=rates();m.commissionDeposit=m.deposit*(r.d1+r.d2+r.d3);m.commissionWithdrawal=m.withdrawal*r.w;m.commission=m.commissionDeposit+m.commissionWithdrawal;m.totalMovement=m.deposit+m.withdrawal+m.cash+m.upline;return m}
app.post('/api/login',(req,res)=>{const{email,password}=req.body||{},u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(String(email||'').trim().toLowerCase());if(!u||!bcrypt.compareSync(String(password||''),u.password_hash))return res.status(401).json({error:'Invalid email or password'});const token=jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role},SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/bootstrap',auth,(req,res)=>res.json({user:req.user,settings:settings(),metrics:metrics(),types:['deposit','withdrawal','cash','upline']}));app.get('/api/transactions',auth,(req,res)=>res.json({rows:rowsFor(req.query.from,req.query.to,req.query.type,req.query.search)}));
app.post('/api/transactions',auth,(req,res)=>{const{tx_date,type,amount,notes}=req.body||{},n=Number(amount);if(!/^\d{4}-\d{2}-\d{2}$/.test(tx_date||'')||!['deposit','withdrawal','cash','upline'].includes(type)||!Number.isFinite(n)||n<=0)return res.status(400).json({error:'Valid date, type and positive amount are required'});const now=new Date().toISOString(),i=db.prepare('INSERT INTO transactions(tx_date,type,amount,notes,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(tx_date,type,n,String(notes||'').slice(0,500),now,now);res.json({id:i.lastInsertRowid})});
app.put('/api/transactions/:id',auth,(req,res)=>{const{tx_date,type,amount,notes}=req.body||{},n=Number(amount);if(!/^\d{4}-\d{2}-\d{2}$/.test(tx_date||'')||!['deposit','withdrawal','cash','upline'].includes(type)||!Number.isFinite(n)||n<=0)return res.status(400).json({error:'Invalid transaction'});const i=db.prepare('UPDATE transactions SET tx_date=?,type=?,amount=?,notes=?,updated_at=? WHERE id=?').run(tx_date,type,n,String(notes||'').slice(0,500),new Date().toISOString(),req.params.id);if(!i.changes)return res.status(404).json({error:'Transaction not found'});res.json({ok:true})});
app.delete('/api/transactions/:id',auth,(req,res)=>{const i=db.prepare('DELETE FROM transactions WHERE id=?').run(req.params.id);if(!i.changes)return res.status(404).json({error:'Transaction not found'});res.json({ok:true})});app.get('/api/metrics',auth,(req,res)=>res.json(metrics(req.query.from,req.query.to)));app.get('/api/settings',auth,(req,res)=>res.json(settings()));
app.put('/api/settings',auth,(req,res)=>{for(const k of['deposit_commission_1','deposit_commission_2','deposit_commission_3','withdrawal_commission'])if(req.body[k]!==undefined){const n=Number(req.body[k]);if(!Number.isFinite(n)||n<0||n>1)return res.status(400).json({error:'Commission must be between 0 and 100%'});db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(n))}res.json(settings())});
function payload(req){const from=req.query.from||'',to=req.query.to||'',rows=rowsFor(from,to,req.query.type,req.query.search),m=metrics(from,to);return{from,to,rows,m,rates:rates()}}
function csvEsc(v){return'"'+String(v??'').replaceAll('"','""')+'"'}
app.get('/api/export',auth,(req,res)=>{const{rows}=payload(req),csv=['Date,Type,Amount,Notes,Created At,Updated At',...rows.map(r=>[r.tx_date,r.type,r.amount,r.notes,r.created_at,r.updated_at].map(csvEsc).join(','))].join('\n');res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="commission-ledger-report.csv"');res.send('\ufeff'+csv)});
app.get('/api/export.xlsx',auth,(req,res)=>{const{rows,m}=payload(req),summary=[['COMMISSION LEDGER — MANAGEMENT REPORT'],['Report Period',req.query.from||'All time','To',req.query.to||'All time'],[],['KPI','Amount'],['Total Deposit',m.deposit],['Total Withdrawal',m.withdrawal],['Total Hawala / Cash',m.cash],['Total Upline',m.upline],['Closing Balance',m.balance],['Deposit Commission',m.commissionDeposit],['Withdrawal Commission',m.commissionWithdrawal],['Total Commission',m.commission],['Total Entries',rows.length]],detail=[['Date','Type','Amount','Notes','Created At','Updated At'],...rows.map(r=>[r.tx_date,r.type,r.amount,r.notes,r.created_at,r.updated_at])],wb=XLSX.utils.book_new(),ws1=XLSX.utils.aoa_to_sheet(summary),ws2=XLSX.utils.aoa_to_sheet(detail);ws1['!cols']=[{wch:28},{wch:18},{wch:18},{wch:18}];ws2['!cols']=[{wch:14},{wch:18},{wch:18},{wch:42},{wch:25},{wch:25}];XLSX.utils.book_append_sheet(wb,ws1,'Summary');XLSX.utils.book_append_sheet(wb,ws2,'Transactions');const out=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="commission-ledger-report.xlsx"');res.send(out)});
app.get('/api/report.pdf',auth,(req,res)=>{const{rows,m,from,to,rates}=payload(req),doc=new PDFDocument({size:'A4',margin:42,bufferPages:true});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="commission-ledger-professional-report.pdf"');doc.pipe(res);const W=doc.page.width-84,fmt=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}),type=t=>({deposit:'DEPOSIT',withdrawal:'WITHDRAWAL',cash:'HAWALA / CASH',upline:'UPLINE'}[t]||String(t).toUpperCase());
const header=()=>{doc.save();doc.rect(42,32,W,54).fill('#111827');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(18).text('COMMISSION LEDGER',58,47);doc.font('Helvetica').fontSize(8).fillColor('#cbd5e1').text('PROFESSIONAL COMMISSION & TRANSACTION STATEMENT',58,69);doc.font('Helvetica-Bold').fontSize(8).fillColor('#fff').text('MANAGEMENT REPORT',W-5,56,{align:'right',width:85});doc.restore()};const card=(x,y,w,h,title,value,sub)=>{doc.roundedRect(x,y,w,h,7).lineWidth(.7).stroke('#e2e8f0');doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(7).text(title.toUpperCase(),x+10,y+10,{width:w-20});doc.fillColor('#111827').font('Helvetica-Bold').fontSize(13).text(fmt(value),x+10,y+25,{width:w-20});doc.fillColor('#64748b').font('Helvetica').fontSize(7).text(sub,x+10,y+43,{width:w-20})};const section=(title,y)=>{doc.fillColor('#111827').font('Helvetica-Bold').fontSize(11).text(title,42,y);return y+18};const tableHead=(y,cols)=>{doc.rect(42,y,W,22).fill('#111827');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(7);cols.forEach(c=>doc.text(c[0],c[1],y+7,{width:c[2]||80}));return y+22};
header();doc.fillColor('#111827').font('Helvetica-Bold').fontSize(16).text('Commission Statement',42,108);doc.font('Helvetica').fontSize(9).fillColor('#64748b').text(`Period: ${from||'All dates'}  —  ${to||'All dates'}`,42,130);doc.text(`Generated: ${new Date().toLocaleString()}`,42,144);let y=168,g=8,cw=(W-g*3)/4;card(42,y,cw,60,'Closing Balance',m.balance,'Net ledger position');card(42+cw+g,y,cw,60,'Total Deposit',m.deposit,`${m.depositCount} entries`);card(42+(cw+g)*2,y,cw,60,'Total Withdrawal',m.withdrawal,`${m.withdrawalCount} entries`);card(42+(cw+g)*3,y,cw,60,'Total Commission',m.commission,'Earned commission');y+=78;
y=section('Commission Breakdown',y);doc.rect(42,y,W,22).fill('#f1f5f9');doc.fillColor('#334155').font('Helvetica-Bold').fontSize(8).text('COMMISSION STREAM',52,y+7);doc.text('RATE',250,y+7);doc.text('BASE',315,y+7);doc.text('COMMISSION',430,y+7);y+=22;[['Deposit Level 1',rates.d1,m.deposit,m.deposit*rates.d1],['Deposit Level 2',rates.d2,m.deposit,m.deposit*rates.d2],['Deposit Level 3',rates.d3,m.deposit,m.deposit*rates.d3],['Withdrawal',rates.w,m.withdrawal,m.withdrawal*rates.w]].forEach((r,i)=>{if(i%2===0)doc.rect(42,y,W,20).fill('#fafafa');doc.fillColor('#334155').font('Helvetica').fontSize(8).text(r[0],52,y+6);doc.text((r[1]*100).toFixed(2)+'%',250,y+6);doc.text(fmt(r[2]),315,y+6);doc.font('Helvetica-Bold').text(fmt(r[3]),430,y+6);y+=20});doc.fillColor('#111827').font('Helvetica-Bold').fontSize(9).text('TOTAL COMMISSION',315,y+6);doc.text(fmt(m.commission),430,y+6);y+=38;
y=section('Transaction Summary',y);doc.rect(42,y,W,22).fill('#f1f5f9');doc.fillColor('#334155').font('Helvetica-Bold').fontSize(8).text('STREAM',52,y+7);doc.text('ENTRIES',300,y+7);doc.text('AMOUNT',430,y+7);y+=22;[['Deposit',m.deposit,m.depositCount],['Withdrawal',m.withdrawal,m.withdrawalCount],['Hawala / Cash',m.cash,m.cashCount],['Upline',m.upline,m.uplineCount]].forEach((r,i)=>{if(i%2===0)doc.rect(42,y,W,22).fill('#fafafa');doc.fillColor('#334155').font('Helvetica').fontSize(8).text(r[0],52,y+7);doc.text(String(r[2]),300,y+7);doc.font('Helvetica-Bold').text(fmt(r[1]),430,y+7);y+=22});
function newPage(title){doc.addPage();header();doc.fillColor('#111827').font('Helvetica-Bold').fontSize(11).text(title,42,108);return 126}y=newPage('Detailed Transaction Register');y=tableHead(y,[['DATE',48,55],['TYPE',114,72],['AMOUNT',196,82],['NOTES',291,150],['ENTRY ID',452,60]]);rows.forEach((r,i)=>{if(y>750){y=newPage('Detailed Transaction Register — continued');y=tableHead(y,[['DATE',48,55],['TYPE',114,72],['AMOUNT',196,82],['NOTES',291,150],['ENTRY ID',452,60]])}if(i%2===0)doc.rect(42,y,W,21).fill('#f8fafc');doc.fillColor('#334155').font('Helvetica').fontSize(7).text(r.tx_date,48,y+6,{width:55});doc.text(type(r.type),114,y+6,{width:72});doc.font('Helvetica-Bold').text(fmt(r.amount),196,y+6,{width:82});doc.font('Helvetica').text(String(r.notes||'—').slice(0,42),291,y+6,{width:150});doc.text(String(r.id),452,y+6);y+=21});const range=doc.bufferedPageRange();for(let i=range.start;i<range.start+range.count;i++){doc.switchToPage(i);doc.fillColor('#64748b').font('Helvetica').fontSize(7).text('Commission Ledger • Confidential Management Report',42,doc.page.height-28);doc.text(`Page ${i+1} of ${range.count}`,doc.page.width-120,doc.page.height-28,{width:78,align:'right'})}doc.end()});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'commission-ledger',time:new Date().toISOString()}));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Commission Ledger running on ${PORT}`));