const express=require('express'); const path=require('path'); const fs=require('fs'); const Database=require('better-sqlite3'); const jwt=require('jsonwebtoken'); const bcrypt=require('bcryptjs'); const helmet=require('helmet'); const morgan=require('morgan');
const app=express(); const PORT=process.env.PORT||3000; const SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
fs.mkdirSync(path.join(__dirname,'data'),{recursive:true}); const db=new Database(path.join(__dirname,'data','ledger.db')); db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'ADMIN',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,tx_date TEXT NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL DEFAULT 0,notes TEXT DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);
const count=db.prepare('SELECT COUNT(*) c FROM users').get().c; if(!count){const hash=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'Admin@12345',10);db.prepare('INSERT INTO users(name,email,password_hash,role,created_at) VALUES(?,?,?,?,?)').run('Administrator',process.env.ADMIN_EMAIL||'admin@local.test',hash,'ADMIN',new Date().toISOString());}
const defaults={deposit_commission_1:'0.01',deposit_commission_2:'0.005',deposit_commission_3:'0.02',withdrawal_commission:'0.015',date_format:'YYYY-MM-DD'}; for(const [k,v] of Object.entries(defaults)) db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v);
app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true})); app.use(morgan('tiny')); app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){try{const h=req.headers.authorization||''; if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired session'})}}
function settings(){return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]));}
function rates(){const s=settings();return {d1:+s.deposit_commission_1,d2:+s.deposit_commission_2,d3:+s.deposit_commission_3,w:+s.withdrawal_commission};}
function metrics(from,to){let where='';const p=[];if(from){where+=' AND tx_date>=?';p.push(from)}if(to){where+=' AND tx_date<=?';p.push(to)}const rows=db.prepare(`SELECT type,SUM(amount) total,COUNT(*) count FROM transactions WHERE 1=1 ${where} GROUP BY type`).all(...p);const m={deposit:0,withdrawal:0,cash:0,upline:0,depositCount:0,withdrawalCount:0,cashCount:0,uplineCount:0};rows.forEach(r=>{m[r.type]=r.total||0;m[r.type+'Count']=r.count||0});m.balance=m.deposit-m.withdrawal-m.cash-m.upline;const r=rates();m.commission=m.deposit*(r.d1+r.d2+r.d3)+m.withdrawal*r.w;return m}
app.post('/api/login',(req,res)=>{const {email,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(String(email||'').trim().toLowerCase());if(!u||!bcrypt.compareSync(String(password||''),u.password_hash))return res.status(401).json({error:'Invalid email or password'});const token=jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role},SECRET,{expiresIn:'12h'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/bootstrap',auth,(req,res)=>res.json({user:req.user,settings:settings(),metrics:metrics(),types:['deposit','withdrawal','cash','upline']}));
app.get('/api/transactions',auth,(req,res)=>{const {from,to,type,search}=req.query;let q='SELECT * FROM transactions WHERE 1=1',p=[];if(from){q+=' AND tx_date>=?';p.push(from)}if(to){q+=' AND tx_date<=?';p.push(to)}if(type){q+=' AND type=?';p.push(type)}if(search){q+=' AND notes LIKE ?';p.push('%'+search+'%')}q+=' ORDER BY tx_date DESC,id DESC';res.json({rows:db.prepare(q).all(...p)});});
app.post('/api/transactions',auth,(req,res)=>{const {tx_date,type,amount,notes}=req.body||{};const allowed=['deposit','withdrawal','cash','upline'];const n=Number(amount);if(!/^\d{4}-\d{2}-\d{2}$/.test(tx_date||'')||!allowed.includes(type)||!Number.isFinite(n)||n<=0)return res.status(400).json({error:'Valid date, type and positive amount are required'});const now=new Date().toISOString();const info=db.prepare('INSERT INTO transactions(tx_date,type,amount,notes,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(tx_date,type,n,String(notes||'').slice(0,500),now,now);res.json({id:info.lastInsertRowid});});
app.put('/api/transactions/:id',auth,(req,res)=>{const {tx_date,type,amount,notes}=req.body||{};const n=Number(amount);if(!/^\d{4}-\d{2}-\d{2}$/.test(tx_date||'')||!['deposit','withdrawal','cash','upline'].includes(type)||!Number.isFinite(n)||n<=0)return res.status(400).json({error:'Invalid transaction'});const info=db.prepare('UPDATE transactions SET tx_date=?,type=?,amount=?,notes=?,updated_at=? WHERE id=?').run(tx_date,type,n,String(notes||'').slice(0,500),new Date().toISOString(),req.params.id);if(!info.changes)return res.status(404).json({error:'Transaction not found'});res.json({ok:true});});
app.delete('/api/transactions/:id',auth,(req,res)=>{const info=db.prepare('DELETE FROM transactions WHERE id=?').run(req.params.id);if(!info.changes)return res.status(404).json({error:'Transaction not found'});res.json({ok:true});});
app.get('/api/metrics',auth,(req,res)=>res.json(metrics(req.query.from,req.query.to)));
app.get('/api/settings',auth,(req,res)=>res.json(settings()));
app.put('/api/settings',auth,(req,res)=>{const allowed=['deposit_commission_1','deposit_commission_2','deposit_commission_3','withdrawal_commission'];for(const k of allowed)if(req.body[k]!==undefined){const n=Number(req.body[k]);if(!Number.isFinite(n)||n<0||n>1)return res.status(400).json({error:'Commission must be between 0 and 100%'});db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(n));}res.json(settings())});
app.get('/api/export',auth,(req,res)=>{const rows=db.prepare('SELECT tx_date,type,amount,notes,created_at,updated_at FROM transactions ORDER BY tx_date,id').all();const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=['Date,Type,Amount,Notes,Created At,Updated At',...rows.map(r=>[r.tx_date,r.type,r.amount,r.notes,r.created_at,r.updated_at].map(esc).join(','))].join('\n');res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition','attachment; filename="commission-ledger-export.csv"');res.send(csv)});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html'))); app.listen(PORT,()=>console.log(`Commission Ledger running on ${PORT}`));
